apiVersion: v1
kind: Template
labels:
  template: sonatype-nexus-template
metadata:
  annotations:
    description: 'Sonatype Nexus Maven repository, it requests no volume claims, so volumes must be added manually. \
        WARNING: If no volumes are added, all changes will be lost when the container exits. Scaling to more than one replica is not supported.'
    iconClass: icon-nexus
    tags: maven,nexus,sonatype
  creationTimestamp: null
  name: sonatype-nexus
objects:

# Service
- apiVersion: v1
  kind: Service
  metadata:
    name: ${NEXUS_SERVICE_NAME}
  spec:
    ports:
    - name: http
      port: 8081
    selector:
      name: ${NEXUS_SERVICE_NAME}

# Route
- apiVersion: v1
  id: ${NEXUS_SERVICE_NAME}-http
  kind: Route
  metadata:
    annotations:
      description: Route for the repository's http service.
    labels:
    name: ${NEXUS_SERVICE_NAME}
  spec:
    host: ${HOSTNAME_HTTP}
    to:
      name: ${NEXUS_SERVICE_NAME}

# Deployment Config
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: ${NEXUS_SERVICE_NAME}
  spec:
    replicas: 1
    selector:
      name: ${NEXUS_SERVICE_NAME}
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          name: ${NEXUS_SERVICE_NAME}
      spec:
        containers:
        - name: ${NEXUS_SERVICE_NAME}
          env:
          - name: TEST_VAR
            value: 'test'
          image: 'docker.io/sonatype/nexus'
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /nexus
              port: 8081
            initialDelaySeconds: 30
            timeoutSeconds: 3
          ports:
          - containerPort: 8081
          readinessProbe:
            httpGet:
              path: /nexus
              port: 8081
            initialDelaySeconds: 30
            timeoutSeconds: 60
          resources:
            limits:
              memory: ${MEMORY_LIMIT}
          volumeMounts:
          - mountPath: /sonatype-work
            name: ${NEXUS_SERVICE_NAME}-data
        volumes:
        - emptyDir:
            medium: ""
          name: ${NEXUS_SERVICE_NAME}-data

parameters:
- description: Maximum amount of memory the container can use.
  displayName: Memory Limit
  name: MEMORY_LIMIT
  required: true
  value: 1Gi
- description: The OpenShift Namespace where the ImageStream resides.
  displayName: Namespace
  name: NAMESPACE
  value: openshift
- description: The name of the OpenShift Service exposed for the repository.
  displayName: Repository Service Name
  name: NEXUS_SERVICE_NAME
  required: true
  value: sonatype-nexus
- description: 'Custom hostname for http service route.  Leave blank for default hostname,
    e.g.: <application-name>-<project>.<default-domain-suffix>'
  displayName: Repository Hostname
  name: HOSTNAME_HTTP

