apiVersion: v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/image.dockerRepositoryCheck: 2016-09-24T14:49:01Z
  creationTimestamp: null
  generation: 2
  name: mariadb
spec:
  tags:
  - annotations:
      description: Provides a MariaDB v10.1 database
      iconClass: icon-mariadb
      tags: mariadb
      version: "10.1"
    from:
      kind: DockerImage
      name: 172.30.103.204:5000/openshift/mariadb:10.1
    generation: 2
    importPolicy: {}
    name: "10.1"
  - annotations:
      description: Provides a MariaDB database
      iconClass: icon-mariadb
      tags: mariadb
    from:
      kind: DockerImage
      name: 172.30.103.204:5000/openshift/mariadb:latest
    generation: 1
    importPolicy: {}
    name: latest
status:
  dockerImageRepository: ""
